//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrix
    {
        public int Id { get; set; }
        public Nullable<int> BuildingPartId { get; set; }
        public Nullable<int> DefectDescriptionId { get; set; }
        public int ImportanceId { get; set; }
        public int IntencityId { get; set; }
        public int ExtentId { get; set; }
        public int Condition { get; set; }
        public Nullable<int> ActieId { get; set; }
        public int HvhId { get; set; }
        public int EenhId { get; set; }
        public Nullable<float> Percent { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Total { get; set; }
        public int BTW { get; set; }
        public int Cycle { get; set; }
        public int StartYear { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
